### ISSUE TITLE
x.mod(BigNumber(1)) should be BigNumber(0) not 0

### ISSUE THREAD

**Issue by dramforever** [alexbardas/bignumber.js#11]
Expected:

    const B = require('big-number');
    B(4).mod(B(2)) // => B(0)
    B(4).mod(B(1)) // => B(0)

Actual

    const B = require('big-number');
    B(4).mod(B(2)) // => B(0)
    B(4).mod(B(1)) // => 0

This bug or special case makes `mod` very difficult to use generally. For example, this `gcd` algorithm is incorrect (crashes on some inputs, say `gcd(2, 1)`) because sometimes `b` will become a non-`BigNumber` and the `equals` call will fail:

    function gcd(a, b) {
        while (! b.equals(0))
            [a, b] = [b, B(a).mod(b)];
        return a;
    }

**Comment by alexbardas** [comment]
Thanks a lot for reporting this @dramforever. It has been fixed in big-number@1.0.0.
