### ISSUE TITLE
Weird behavior on comparison

### ISSUE THREAD

**Issue by dannydeezy** [alexbardas/bignumber.js#16]
```
> let bn = require('big-number')
> let a = bn('5929390')
> let b = bn('852523')
> aa < bb
true
```
Super weird. The comparison is wrong.

**Comment by petr-ujezdsky** [comment]
You are comparing objects, not numbers. You just wrote something like `{} < {}`.
See `gt, lt` etc:
> Supported methods: add/plus, minus/subtract, multiply/mult, divide/div, power/pow, mod, equals, lt, lte, gt, gte, isZero, abs

**Comment by dannydeezy** [comment]
> You are comparing objects, not numbers. You just wrote something like `{} < {}`.
> See `gt, lt` etc:
> 
> > Supported methods: add/plus, minus/subtract, multiply/mult, divide/div, power/pow, mod, equals, lt, lte, gt, gte, isZero, abs

Silly me. Good catch thanks!
